### ISSUE TITLE
Session goes bad after ~1 hour of inactivity

### ISSUE THREAD

**Issue by mangstadt** [mangstadt/emc-shopkeeper#17]
1. User updates transactions.
2. Leaves app open for ~1 hour
3. User updates transactions again.  A NPE is thrown.

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><Error><Timestamp>2015-09-21 23:21:31Z</Timestamp><Version>0.5.4</Version><DatabaseVersion>30</DatabaseVersion><JavaVersion>1.8.0_60</JavaVersion><OS>Windows 8.1</OS><Locale>en_US</Locale><WebStart>false</WebStart><StackTrace>java.lang.NullPointerException&#13;
	at com.github.mangstadt.emc.rupees.RupeeTransactionReader.&lt;init&gt;(RupeeTransactionReader.java:90)&#13;
	at com.github.mangstadt.emc.rupees.RupeeTransactionReader.&lt;init&gt;(RupeeTransactionReader.java:40)&#13;
	at com.github.mangstadt.emc.rupees.RupeeTransactionReader$Builder.build(RupeeTransactionReader.java:552)&#13;
	at emcshop.model.UpdateModelImpl$DownloadThread.run(UpdateModelImpl.java:225)&#13;
</StackTrace></Error>
```

**Comment by mangstadt** [comment]
An error occurs because the session has timed out.  Because there is a `EmcSession` object in the `AppContext`, it assumes it's still valid and can be re-used.

When the `RupeeTransactionReader` object tries to tries parsing the first transaction page (in order to get the date of the latest transaction), it throws a NPE because the HTML page that was returned was not a rupee transaction page (the session was not valid, so some other HTML page was returned).

**Comment by mangstadt** [comment]
https://github.com/mangstadt/emc-shopkeeper/commit/157a9c009e53ca3f261bcc28fc43d61c9a770e8e
