### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by mangstadt** [mangstadt/emc-shopkeeper#18]
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><Error><Timestamp>2015-09-13 20:03:18Z</Timestamp><Version>0.5.4</Version><DatabaseVersion>30</DatabaseVersion><JavaVersion>1.8.0_60</JavaVersion><OS>Windows 8.1</OS><Locale>en_US</Locale><WebStart>false</WebStart><StackTrace>java.lang.NullPointerException&#13;
	at emcshop.gui.InventoryTab$InventoryTable$InventoryTableModel.setValueAt(InventoryTab.java:580)&#13;
	at javax.swing.JTable.setValueAt(Unknown Source)&#13;
	at javax.swing.JTable.editingStopped(Unknown Source)&#13;
	at javax.swing.AbstractCellEditor.fireEditingStopped(Unknown Source)&#13;
	at javax.swing.AbstractCellEditor.stopCellEditing(Unknown Source)&#13;
	at javax.swing.plaf.basic.BasicTableUI$Handler.mousePressed(Unknown Source)&#13;
	at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)&#13;
	at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)&#13;
	at java.awt.Component.processMouseEvent(Unknown Source)&#13;
	at javax.swing.JComponent.processMouseEvent(Unknown Source)&#13;
	at java.awt.Component.processEvent(Unknown Source)&#13;
	at java.awt.Container.processEvent(Unknown Source)&#13;
	at java.awt.Component.dispatchEventImpl(Unknown Source)&#13;
	at java.awt.Container.dispatchEventImpl(Unknown Source)&#13;
	at java.awt.Component.dispatchEvent(Unknown Source)&#13;
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)&#13;
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)&#13;
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)&#13;
	at java.awt.Container.dispatchEventImpl(Unknown Source)&#13;
	at java.awt.Window.dispatchEventImpl(Unknown Source)&#13;
	at java.awt.Component.dispatchEvent(Unknown Source)&#13;
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)&#13;
	at java.awt.EventQueue.access$500(Unknown Source)&#13;
	at java.awt.EventQueue$3.run(Unknown Source)&#13;
	at java.awt.EventQueue$3.run(Unknown Source)&#13;
	at java.security.AccessController.doPrivileged(Native Method)&#13;
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)&#13;
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)&#13;
	at java.awt.EventQueue$4.run(Unknown Source)&#13;
	at java.awt.EventQueue$4.run(Unknown Source)&#13;
	at java.security.AccessController.doPrivileged(Native Method)&#13;
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)&#13;
	at java.awt.EventQueue.dispatchEvent(Unknown Source)&#13;
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)&#13;
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)&#13;
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)&#13;
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)&#13;
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)&#13;
	at java.awt.EventDispatchThread.run(Unknown Source)&#13;
</StackTrace></Error>
```

**Comment by mangstadt** [comment]
Fixed in: https://github.com/mangstadt/emc-shopkeeper/commit/ebac0634167085701f219e33818e3f1e3c661f0d
