### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by mangstadt** [mangstadt/emc-shopkeeper#19]
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><Error><Timestamp>2015-08-21 04:13:54Z</Timestamp><Version>0.5.4</Version><DatabaseVersion>30</DatabaseVersion><JavaVersion>1.8.0_25</JavaVersion><OS>Windows 8.1</OS><Locale>en_GB</Locale><WebStart>false</WebStart><StackTrace>java.lang.NullPointerException&#13;
	at emcshop.gui.PaymentsTab$PaymentsTable$4.compare(PaymentsTab.java:330)&#13;
	at emcshop.gui.PaymentsTab$PaymentsTable$4.compare(PaymentsTab.java:327)&#13;
	at javax.swing.DefaultRowSorter.compare(Unknown Source)&#13;
	at javax.swing.DefaultRowSorter.access$100(Unknown Source)&#13;
	at javax.swing.DefaultRowSorter$Row.compareTo(Unknown Source)&#13;
	at javax.swing.DefaultRowSorter$Row.compareTo(Unknown Source)&#13;
	at java.util.Arrays.binarySearch0(Unknown Source)&#13;
	at java.util.Arrays.binarySearch(Unknown Source)&#13;
	at javax.swing.DefaultRowSorter.insertInOrder(Unknown Source)&#13;
	at javax.swing.DefaultRowSorter.rowsUpdated0(Unknown Source)&#13;
	at javax.swing.DefaultRowSorter.rowsUpdated(Unknown Source)&#13;
	at javax.swing.DefaultRowSorter.rowsUpdated(Unknown Source)&#13;
	at javax.swing.JTable.notifySorter(Unknown Source)&#13;
	at javax.swing.JTable.sortedTableChanged(Unknown Source)&#13;
	at javax.swing.JTable.tableChanged(Unknown Source)&#13;
	at javax.swing.table.AbstractTableModel.fireTableChanged(Unknown Source)&#13;
	at javax.swing.table.AbstractTableModel.fireTableCellUpdated(Unknown Source)&#13;
	at emcshop.gui.PaymentsTab$PaymentsTable$Renderer$1$1.run(PaymentsTab.java:433)&#13;
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)&#13;
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)&#13;
	at java.awt.EventQueue.access$400(Unknown Source)&#13;
	at java.awt.EventQueue$3.run(Unknown Source)&#13;
	at java.awt.EventQueue$3.run(Unknown Source)&#13;
	at java.security.AccessController.doPrivileged(Native Method)&#13;
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)&#13;
	at java.awt.EventQueue.dispatchEvent(Unknown Source)&#13;
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)&#13;
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)&#13;
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)&#13;
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)&#13;
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)&#13;
	at java.awt.EventDispatchThread.run(Unknown Source)&#13;
</StackTrace></Error>
```

**Comment by mangstadt** [comment]
Fixed in: https://github.com/mangstadt/emc-shopkeeper/commit/8cb9815ff7be95a6ede63a8ae293e277007ca21e
