### ISSUE TITLE
Transaction download errors out at page 42

### ISSUE THREAD

**Issue by mangstadt** [mangstadt/emc-shopkeeper#32]
While a user is downloading her transaction history, the download process errors out at page 42.

```
java.io.IOException: A problem occurred downloading page 42.
	at com.github.mangstadt.emc.rupees.RupeeTransactionReader$ScrapeThread.run(RupeeTransactionReader.java:378)
Caused by: java.lang.NullPointerException
	at com.github.mangstadt.emc.rupees.RupeeTransactionReader$ScrapeThread.run(RupeeTransactionReader.java:322)
```

**Comment by mangstadt** [comment]
The problem was that the date/time format of transactions older than one week were formatted in 24-hour time. EMC Shopkeeper was expecting 12-hour time.

The user's date/time settings in their EMC account were set to 24-hour time. When they changed it to 12-hour time, they were able to download their transactions. So, this setting apparently affects the rupee transaction timestamps too.

Fixed in: https://github.com/mangstadt/emc-rupee-transaction-downloader/commit/30ba68f417d02dd68947bfcc37d893de3d625137
