### ISSUE TITLE
IllegalArgumentException on startup

### ISSUE THREAD

**Issue by mangstadt** [mangstadt/emc-shopkeeper#41]
The following exception is being thrown on startup for a number of users:

```
java.lang.IllegalArgumentException: Multiple entries with same key: Grass Block=jar:file:/home/emma/Downloads/emc-shopkeeper-full.jar!/emcshop/gui/images/items/grass_block.png and Grass Block=jar:file:/home/emma/Downloads/emc-shopkeeper-full.jar!/emcshop/gui/images/items/grass_block.png
    at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:215)
    at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:209)
    at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:146)
    at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:109)
    at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:394)
    at emcshop.gui.ItemSuggestField.init(ItemSuggestField.java:74)
    at emcshop.EMCShopkeeper.launchGui(EMCShopkeeper.java:462)
    at emcshop.EMCShopkeeper.main(EMCShopkeeper.java:218)
```

https://empireminecraft.com/threads/useful-tool-emc-shopkeeper.22507/page-35#post-1585057

**Comment by mangstadt** [comment]
In the previous update, the following database upgrade SQL statement was called:

```sql
UPDATE items SET name='Grass Block' WHERE name='Grass';
```
(source: https://github.com/mangstadt/emc-shopkeeper/blob/master/src/main/resources/emcshop/db/migrate-48-49.sql)

This was done in order to resolve an item name mapping issue. The assumption was that no items with a name of "Grass Block" existed in that table. This assumption was true for my personal database, but not true for other users.

Solution: Remove duplicate item names in the database upgrade script for next version.

Fixed in 299d954648377fbda345e61a15a5dfeeadb10703
